version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    build: ./frontend/
    env_file: .env
    volumes:
      - static:/static
    command: cp -r /app/build/. /static/

  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    ports:
      - 7000:80
